app/front_end/__init__.py
__author__ = 'jie'

from flask import Blueprint

front_end = Blueprint('front_end', __name__, static_folder='static', template_folder='templates')

from . import views

app/front_end/views.py
__author__ = 'jie'

from flask import send_file, render_template, current_app
from flask_user import login_required
from . import front_end

@front_end.route("/")
@login_required
def index():
    api_prefix = "/api/v1.0"
    if 'ROUTE_PREFIX' in current_app.config:
        api_prefix = "/" + current_app.config['ROUTE_PREFIX'] + api_prefix
    return render_template('front_end.html', api_prefix=api_prefix, route_prefix=current_app.config['ROUTE_PREFIX'])

app/front_end/templates/front_end.html
{% extends "front_end_base.html" %}

{% block styles %}
    {{ super() }}
    <link rel="stylesheet" type="text/css" href="{{ url_for('bower.static', filename='morrisjs/morris.css') }}">
    <link rel="stylesheet" type="text/css" href="{{ url_for('bower.static', filename='angular-bootstrap/ui-bootstrap-csp.css') }}">
{% endblock %}

{% block body_attribs %} ng-app="postOrdersApp" ng-strict-di api_prefix="{{ api_prefix }}" route_prefix="{{route_prefix}}" {% endblock %}

{% block content %}
<div id="wrapper" ng-controller="Frame">
    <nav class="navbar navbar-default navbar-fixed-top" role="navigation" style="margin-bottom: 0">
        <div class="navbar-header">
            <button type="button" class="navbar-toggle" data-toggle="collapse" data-target=".navbar-collapse">
                <span class="sr-only">Toggle navigation</span>
                <span class="icon-bar"></span>
                <span class="icon-bar"></span>
                <span class="icon-bar"></span>
            </button>
            <a class="navbar-brand" href="{{ url_for('front_end.index')}}#/"><i class="fa fa-truck"></i> 西安线 订单管理</a>
        </div>
        <!-- /.navbar-header -->

        <ul class="nav navbar-top-links navbar-right">
            <li class="top-half-buffer">

            </li>
        </ul>

        <!-- /.navbar-top-links -->

        <div class="navbar-default sidebar" role="navigation">
            <div class="sidebar-nav navbar-collapse">
                <ul class="nav" id="side-menu">
                    <li>
                        <a href="#/batch-order" ng-class="{active: isActive('/batch-order')}"><i class="fa fa-print"></i> 生成订单</a>
                    </li>

                    <li>
                        <a href="#/retract-orders" ng-class="{active: isActive('/retract-orders')}"><i class="fa fa-check-square-o"></i> 提取订单</a>
                    </li>

                    <li>
                        <a href="#/new-order-numbers" ng-class="{active: isActive('/new-order-numbers')}"><i class="fa fa-upload"></i> 补充订单号</a>
                    </li>

                    <li>
                        <a href="#/scan-barcode" ng-class="{active: isActive('/scan-barcode')}"><i class="fa fa-barcode"></i> Scan Barcode</a>
                    </li>

                    <li>
                        <a href="#/merge-excel" ng-class="{active: isActive('/merge-excel')}"><i class="fa fa-files-o"></i> 合并提取结果</a>
                    </li>

                    <li>
                        <a href="/{[route_prefix]}/admin/admin.success_jobs"><i class="fa fa-clock-o"></i> 历史生成订单下载</a>
                    </li>

                    <li>
                        <a href="/{[route_prefix]}/admin/admin.success_retraction"><i class="fa fa-calendar-check-o"></i> 历史提取订单下载</a>
                    </li>

                    <li>
                        <a href="/{[route_prefix]}/admin/admin.product_info"><i class="fa fa-cubes"></i> 商品信息管理</a>
                    </li>

                    <li>
                        <a href="{{ url_for('user.logout') }}"><i class="fa fa-sign-out"></i> Logout</a>
                    </li>

                    <!--
                    <li>
                        <a href="#"><i class="fa fa-files-o fa-fw"></i> <span class="fa arrow"></span></a>
                        <ul class="nav nav-second-level">
                            <li>
                                <a>a</a>
                            </li>
                            <li>
                                <a>b</a>
                            </li>
                        </ul>

                    </li>

                    <li>
                        <a href="#" ><i class="fa fa-sign-out fa-fw"></i> Logout</a>
                    </li>
                    -->
                </ul>
            </div>
            <!-- /.sidebar-collapse -->
        </div>
        <!-- /.navbar-static-side -->
    </nav>


    <div id="page-wrapper" >
        <div class="row ">
            <div class="col-lg-12">
                <uib-alert ng-repeat="alert in alerts" type="{[alert.type]}" close="closeAlert($index)" class="top-double-buffer">{[alert.msg]}</uib-alert>
            </div>
        </div>

        <div ng-view>

        </div>

    </div>

    <div class="myfooter top-double-buffer">
    Copyright 2016
    </div>
</div>

{% endblock %}
{% block scripts %}
    {{ super() }}
    <script src="{{ url_for('bower.static', filename='metisMenu/dist/metisMenu.min.js') }}"></script>

    <script src="{{ url_for('bower.static', filename='angular/angular.min.js') }}"></script>
    <script src="{{ url_for('bower.static', filename='angular-cookies/angular-cookies.min.js') }}"></script>
    <script src="{{ url_for('bower.static', filename='ng-file-upload/ng-file-upload-shim.js') }}"></script>
    <script src="{{ url_for('bower.static', filename='ng-file-upload/ng-file-upload.js') }}"></script>
    <script src="{{ url_for('bower.static', filename='angular-route/angular-route.min.js') }}"></script>
    <script src="{{ url_for('bower.static', filename='lodash/dist/lodash.min.js') }}"></script>
    <script src="{{ url_for('bower.static', filename='restangular/dist/restangular.min.js') }}"></script>

    <script src="{{ url_for('bower.static', filename='angular-bootstrap/ui-bootstrap-tpls.min.js') }}"></script>



    {% assets filters="jsmin", output="gen/postorders_front_end.js",
        "front_end/js/main.js", "front_end/js/controllers/frame.js",
        "front_end/js/controllers/batch-order.js", "front_end/js/factories/batch-order.js",
        "front_end/js/controllers/new-order-numbers.js", "front_end/js/controllers/retract-orders.js",
        "front_end/js/controllers/scan-barcode.js", "front_end/js/factories/scan-order.js",
        "front_end/js/factories/route-info.js", "front_end/js/controllers/merge-excel.js" %}
        <script type="text/javascript" src="{{ ASSET_URL }}"></script>
    {% endassets %}

{% endblock %}